SHOW databases;
CREATE DATABASE AY2022;
SHOW databases;
USE AY2022;
CREATE TABLE student (ROLL_NO INT(5), STUD_NAME VARCHAR(35), STREAM CHAR(20), MARK1 DECIMAL(6,2), MARK2 DECIMAL(6,2), DOB DATE);
SHOW tables;
DROP table student;
SHOW tables;
CREATE TABLE teacher (TR_ID INT(10), TR_NAME VARCHAR(35), TR_SAL DECIMAL(15,2), ROLL_NO INT(5));
INSERT INTO student VALUES(101, 'Surya Takur', 'Science', 90, 87, '1990/10/10');
INSERT INTO student VALUES(102, 'Chris Tom', 'Humanities', 88, 91, '1994/1/5');
INSERT INTO student VALUES(103, 'Abel George', 'Commerce', 93, 95, '1993/10/7');
INSERT INTO student VALUES(104, 'Nathel Pillai', 'Science', 56, 58, '1994/8/8');
desc student;
DROP TABLE teacher;
CREATE DATABASE school;
DROP DATABASE school;
SELECT * FROM student;
SELECT stud_name, stream FROM STUDENT;
SELECT stud_name FROM student WHERE stream='Science';
SELECT stud_name, mark1, mark2 FROM student WHERE mark1 > 89;
SELECT * FROM student WHERE mark2 BETWEEN 91 AND 95;
SELECT * FROM student WHERE DOB >= '1994-01-01';
SELECT * FROM student WHERE DOB = '1994-01-01';
INSERT INTO student VALUES(110, 'Karthik Kiran', null, 100, null, '1993/10/10');
INSERT INTO student(roll_no, stud_name, dob) VALUES(111, 'Jerry John', '1994/11/19');
SELECT * FROM student WHERE mark1 IS NULL OR mark2 IS NULL;
SELECT * FROM student WHERE mark1 IS NOT NULL OR MARK2 IS NOT NULL;
SELECT DISTINCT stream FROM student;
SELECT roll_no ROLL_NUMBER, stud_name STUDENT_NAME FROM student;
SELECT stud_name, dob FROM student WHERE mark2 IN (91,95);
SELECT * FROM student WHERE year(dob)='1994';
SELECT roll_no, stud_name FROM student WHERE month(dob)='10';
SELECT roll_no, stud_name FROM student where day(dob)>9;
SELECT stream FROM student WHERE stream LIKE "%e%";
SELECT stud_name FROM student WHERE stud_name LIKE "%i%";
SELECT stud_name FROM student WHERE stud_name LIKE "____ %";
SELECT stud_name FROM student WHERE stream LIKE "__m%";
SELECT stud_name, dob FROM student WHERE dob LIKE "%-10-%";
SELECT stud_name FROM student ORDER BY stud_name DESC;
SELECT stud_name, dob FROM student WHERE stream="Science" ORDER BY dob;
SELECT stream FROM student WHERE length(stream)>7;
UPDATE student SET dob="1994-5-1" WHERE roll_no=102;
UPDATE student SET mark1=mark1+2;
UPDATE student SET stud_name="Nithin Pillai" WHERE roll_no=104;
DELETE FROM student WHERE mark1<88 AND mark2<88;
DELETE FROM student;
CREATE VIEW name AS SELECT roll_no, stud_name FROM student WHERE mark1>90 AND mark2>90;
DROP VIEW name;
ALTER TABLE student ADD COLUMN location char(50);
DESC student;
ALTER TABLE student DROP COLUMN location;
DESC student;
ALTER TABLE student MODIFY location varchar(40);
DESC STUDENT;
ALTER TABLE student CHANGE location street varchar(90);
DESC student;
INSERT INTO teacher VALUES(210, 'Rekha Nair', 8500, 102);
INSERT INTO teacher VALUES(999, 'Elias John', 9900, 103);
INSERT INTO teacher VALUES(154, 'Erick D K', 8900, 101);
INSERT INTO student VALUES(101, 'Surya Takur', 'Science', 90, 87, '1990/10/10','Dubai');
INSERT INTO student VALUES(102, 'Chris Tom', 'Humanities', 88, 91, '1994/1/5', 'Abu Dhabi');
INSERT INTO student VALUES(103, 'Abel George', 'Commerce', 93, 95, '1993/10/7', 'Dubai');
INSERT INTO student VALUES(104, 'Nathel Pillai', 'Science', 56, 58, '1994/8/8', 'Dubai');
SELECT SUM(mark1) FROM student;
SELECT MIN(dob), MAX(dob) FROM student;
SELECT COUNT(*) FROM student WHERE mark1>90;
SELECT round(AVG(mark2),2) FROM student WHERE stud_name LIKE "% T%";
SELECT * FROM student WHERE stud_name LIKE "%a%" GROUP BY dob;
SELECT * FROM student GROUP BY dob HAVING stud_name LIKE "%a%";
SELECT stream, COUNT(stud_name) FROM student GROUP BY stream;
SELECT * FROM student, teacher WHERE student.roll_no=teacher.roll_no AND mark1>90;